BlipConfig = {}

BlipConfig.Sprites = {
    { id = 1, name = "Circle" },
    { id = 6, name = "Arrow" },
    { id = 7, name = "North" },
    { id = 38, name = "Race Flag" },
    { id = 40, name = "House" },
    { id = 47, name = "Speech Bubble" },
    { id = 51, name = "Pill" },
    { id = 52, name = "Shopping Basket" },
    { id = 58, name = "Wanted Star" },
    { id = 60, name = "Police Badge" },
    { id = 61, name = "Hospital" },
    { id = 66, name = "Question Mark" },
    { id = 67, name = "Security Van" },
    { id = 68, name = "Tow Hook" },
    { id = 71, name = "Scissors" },
    { id = 72, name = "Spray Can" },
    { id = 73, name = "T-Shirt" },
    { id = 75, name = "Tattoo" },
    { id = 76, name = "A" },
    { id = 77, name = "L" },
    { id = 78, name = "M" },
    { id = 79, name = "T " },
    { id = 80, name = "H" },
    { id = 84, name = "Skull" },
    { id = 85, name = "Tour Bus" },
    { id = 86, name = "F" },
    { id = 89, name = "C" },
    { id = 90, name = "Plane" },
    { id = 93, name = "Cocktail Glass" },
    { id = 94, name = "Parachute" },
    { id = 100, name = "Car Wash" },
    { id = 102, name = "Comedy Glasses" },
    { id = 103, name = "Dartboard" },
    { id = 106, name = "B" },
    { id = 108, name = "Dollar Sign" },
    { id = 109, name = "Golf" },
    { id = 110, name = "Gun" },
    { id = 112, name = "X" },
    { id = 119, name = "Crosshair" },
    { id = 120, name = "S" },
    { id = 121, name = "High Heel" },
    { id = 122, name = "Tennis Racquet" },
    { id = 126, name = "Sprinter" },
    { id = 134, name = "Key" },
    { id = 135, name = "Cinema Camera" },
    { id = 136, name = "Music Note" },
    { id = 140, name = "Cannabis Leaf" },
    { id = 141, name = "Deer" },
    { id = 162, name = "Map Blip" },
    { id = 163, name = "No Entry Sign" },
    { id = 176, name = "Castle" },
    { id = 184, name = "Camera" },
    { id = 188, name = "Handcuffs" },
    { id = 197, name = "Yoga" },
    { id = 198, name = "Taxi" },
    { id = 226, name = "Motorbike" },
    { id = 227, name = "Car" },
    { id = 237, name = "Fence" },
    { id = 266, name = "Ferris Wheel" },
    { id = 267, name = "P" },
    { id = 270, name = "O" },
    { id = 273, name = "Dog Bone" },
    { id = 279, name = "Lips" },
    { id = 280, name = "Man Waving" },
    { id = 303, name = "Bounty Skull" },
    { id = 304, name = "Star" },
    { id = 305, name = "Sheild with Cross" },
    { id = 308, name = "Submarine" },
    { id = 310, name = "Skull and Crossbones" },
    { id = 311, name = "Bicep" },
    { id = 318, name = "Garbage Truck" },
    { id = 354, name = "Lightning Bolt" },
    { id = 355, name = "D" },
    { id = 356, name = "Anchor" },
    { id = 357, name = "Garage" },
    { id = 358, name = "Red Golf Flag" },
    { id = 359, name = "Aircraft Hangar" },
    { id = 360, name = "Helipad" },
    { id = 361, name = "Jerry Can" },
    { id = 362, name = "Mask" },
    { id = 365, name = "Recycling Symbol" },
    { id = 366, name = "Boilersuit" },
    { id = 367, name = "Tick" },
    { id = 368, name = "Rocket" },
    { id = 439, name = "Crown" },
    { id = 442, name = "Wolf" },
    { id = 446, name = "Tools" },
    { id = 590, name = "Globe"},
    { id = 606, name = "Computer"},
    { id = 729, name = "Scuba Gear"},
    { id = 738, name = "G"},
    { id = 739, name = "R"},
    { id = 838, name = "U"},
    { id = 870, name = "Y"},
    { id = 871, name = "V"}
}

BlipConfig.Colors = {
    { id = 0, name = "White", hex = "#FFFFFF" },
    { id = 1, name = "Red", hex = "#F44242" },
    { id = 2, name = "Green", hex = "#42F442" },
    { id = 3, name = "Light Blue", hex = "#4286F4" },
    { id = 5, name = "Yellow", hex = "#F4F442" },
    { id = 7, name = "Violet", hex = "#9B42F4" },
    { id = 8, name = "Baby Pink", hex = "FFE98BD0" },
    { id = 27, name = "Purple", hex = "#9400D3" },
    { id = 38, name = "Dark Blue", hex = "#0000FF" },
    { id = 39, name = "Gray", hex = "#C0C0C0" },
    { id = 46, name = "Gold", hex = "#FFD700" },
    { id = 47, name = "Orange", hex = "#FF7F50" },
    { id = 48, name = "Hot Pink", hex = "#FF55A3" }
}
