BlipConfig = {}

BlipConfig.Sprites = {
    { id = 1, name = "Standard Circle" },
    { id = 2, name = "Big Circle" },
    { id = 3, name = "Small Circle" },
    { id = 4, name = "Upright Circle" },
    { id = 5, name = "Big Upright Circle" },
    { id = 6, name = "Small Upright Circle" },
    { id = 7, name = "Square" },
    { id = 8, name = "Big Square" },
    { id = 9, name = "Small Square" },
    { id = 10, name = "Upright Square" },
    { id = 11, name = "Big Upright Square" },
    { id = 12, name = "Small Upright Square" },
    { id = 13, name = "Triangle" },
    { id = 14, name = "Big Triangle" },
    { id = 15, name = "Small Triangle" },
    { id = 16, name = "Upright Triangle" },
    { id = 17, name = "Big Upright Triangle" },
    { id = 18, name = "Small Upright Triangle" },
    { id = 19, name = "Diamond" },
    { id = 20, name = "Big Diamond" },
    { id = 21, name = "Small Diamond" },
    { id = 22, name = "Upright Diamond" },
    { id = 23, name = "Big Upright Diamond" },
    { id = 24, name = "Small Upright Diamond" },
    { id = 25, name = "GTAO Crosshair" },
    { id = 26, name = "GTAO Circle" },
    { id = 27, name = "GTAO Square" },
    { id = 28, name = "GTAO Triangle" },
    { id = 29, name = "GTAO Diamond" },
    { id = 30, name = "GTAO Star" },
    { id = 31, name = "GTAO Hexagon" },
    { id = 32, name = "GTAO Pentagon" },
    { id = 33, name = "GTAO Octagon" },
    { id = 34, name = "GTAO Arrow" },
    { id = 35, name = "GTAO Marker" },
    { id = 36, name = "GTAO Flag" },
    { id = 37, name = "GTAO Pin" },
    { id = 38, name = "GTAO Waypoint" },
    { id = 39, name = "GTAO Objective" },
    { id = 40, name = "GTAO Mission" },
    { id = 41, name = "GTAO Race" },
    { id = 42, name = "GTAO Deathmatch" },
    { id = 43, name = "GTAO Capture" },
    { id = 44, name = "GTAO Last Team Standing" },
    { id = 45, name = "GTAO Parachute" },
    { id = 46, name = "GTAO Vehicle Deathmatch" },
    { id = 47, name = "GTAO Contact Mission" },
    { id = 48, name = "GTAO Heist" },
    { id = 49, name = "GTAO Special Vehicle" },
    { id = 50, name = "GTAO Stunt Race" },
    { id = 51, name = "GTAO Adversary Mode" },
    { id = 52, name = "GTAO Transform Race" },
    { id = 53, name = "GTAO Target Assault" },
    { id = 54, name = "GTAO Arena War" },
    { id = 55, name = "Simple Waypoint" },
    { id = 56, name = "Numbered 1" },
    { id = 57, name = "Numbered 2" },
    { id = 58, name = "Numbered 3" },
    { id = 59, name = "Numbered 4" },
    { id = 60, name = "Numbered 5" },
    { id = 61, name = "Numbered 6" },
    { id = 62, name = "Numbered 7" },
    { id = 63, name = "Numbered 8" },
    { id = 64, name = "House" },
    { id = 65, name = "Apartment" },
    { id = 66, name = "Garage" },
    { id = 67, name = "Office" },
    { id = 68, name = "Bunker" },
    { id = 69, name = "Hangar" },
    { id = 70, name = "Facility" },
    { id = 71, name = "Nightclub" },
    { id = 72, name = "Maze Bank West" },
    { id = 73, name = "Arcade" },
    { id = 74, name = "Auto Shop" },
    { id = 75, name = "Agency" },
    { id = 76, name = "Record A Studios" },
    { id = 77, name = "Salvage Yard" },
    { id = 78, name = "Multi-Garage" },
    { id = 79, name = "Clubhouse" },
    { id = 80, name = "Counterfeit Cash" },
    { id = 81, name = "Meth Lab" },
    { id = 82, name = "Cocaine Lockup" },
    { id = 83, name = "Document Forgery" },
    { id = 84, name = "Weed Farm" },
    { id = 85, name = "Cargo Warehouse" },
    { id = 86, name = "Vehicle Cargo" },
    { id = 87, name = "Special Cargo" },
    { id = 88, name = "CEO Office" },
    { id = 89, name = "Yacht" },
    { id = 90, name = "Casino" },
    { id = 91, name = "Casino Apartment" },
    { id = 92, name = "Penthouse" },
    { id = 93, name = "Arcade Retro" },
    { id = 94, name = "Terrorbyte" },
    { id = 95, name = "Mobile Operations Center" },
    { id = 96, name = "Avenger" },
    { id = 97, name = "Kostaka" },
    { id = 98, name = "Cayo Perico" },
    { id = 99, name = "Music Locker" },
    { id = 100, name = "Record A Studios 2" },
    { id = 101, name = "Gunrunning" },
    { id = 102, name = "Smuggler" },
    { id = 103, name = "Air Freight" },
    { id = 104, name = "Club Management" },
    { id = 105, name = "Goods" },
    { id = 106, name = "Club" },
    { id = 107, name = "Goods Club" },
    { id = 108, name = "Personal Vehicle" },
    { id = 109, name = "Personal Vehicle Destroyed" },
    { id = 110, name = "Helicopter" },
    { id = 111, name = "Plane" },
    { id = 112, name = "Boat" },
    { id = 113, name = "Car" },
    { id = 114, name = "Bike" },
    { id = 115, name = "Truck" },
    { id = 116, name = "Train" },
    { id = 117, name = "Bus" },
    { id = 118, name = "Taxi" },
    { id = 119, name = "Emergency" },
    { id = 120, name = "Police Station" },
    { id = 121, name = "Hospital" },
    { id = 122, name = "Fire Station" },
    { id = 123, name = "Gun Shop" },
    { id = 124, name = "Clothes Store" },
    { id = 125, name = "Barber" },
    { id = 126, name = "Tattoo" },
    { id = 127, name = "Mod Shop" },
    { id = 128, name = "Ammu-Nation" },
    { id = 129, name = "Convenience Store" },
    { id = 130, name = "Gas Station" },
    { id = 131, name = "Bank" },
    { id = 132, name = "ATM" },
    { id = 133, name = "Car Wash" },
    { id = 134, name = "Bar" },
    { id = 135, name = "Club" },
    { id = 136, name = "Restaurant" },
    { id = 137, name = "Fast Food" },
    { id = 138, name = "Hotel" },
    { id = 139, name = "Motel" },
    { id = 140, name = "Movie Theater" },
    { id = 141, name = "Golf" },
    { id = 142, name = "Tennis" },
    { id = 143, name = "Darts" },
    { id = 144, name = "Bowling" },
    { id = 145, name = "Pool" },
    { id = 146, name = "Strip Club" },
    { id = 147, name = "Casino" },
    { id = 148, name = "Race" },
    { id = 149, name = "Stunt Race" },
    { id = 150, name = "Deathmatch" },
    { id = 151, name = "Capture" },
    { id = 152, name = "Last Team Standing" },
    { id = 153, name = "Mission" },
    { id = 154, name = "Heist" },
    { id = 155, name = "Parachute" },
    { id = 156, name = "Survival" },
    { id = 157, name = "Contact" },
    { id = 158, name = "Safehouse" },
    { id = 159, name = "Crash Site" },
    { id = 160, name = "Criminal" },
    { id = 161, name = "Drugs" },
    { id = 162, name = "Arms Deal" },
    { id = 163, name = "Heist Setup" },
    { id = 164, name = "Package" },
    { id = 165, name = "Crate Drop" },
    { id = 166, name = "Target" },
    { id = 167, name = "Snitch" },
    { id = 168, name = "VIP" },
    { id = 169, name = "Enemy" },
    { id = 170, name = "Police" },
    { id = 171, name = "Swat" },
    { id = 172, name = "FBI" },
    { id = 173, name = "IAA" },
    { id = 174, name = "Merryweather" },
    { id = 175, name = "Gang" },
    { id = 176, name = "Lost MC" },
    { id = 177, name = "Vagos" },
    { id = 178, name = "Ballas" },
    { id = 179, name = "Families" },
    { id = 180, name = "Marabunta" },
    { id = 181, name = "Triad" },
    { id = 182, name = "Cartel" },
    { id = 183, name = "Kkangpae" },
    { id = 184, name = "Altruist" },
    { id = 185, name = "Cult" },
    { id = 186, name = "Human Trafficking" },
    { id = 187, name = "Prostitute" },
    { id = 188, name = "Pimp" },
    { id = 189, name = "Drug Dealer" },
    { id = 190, name = "Weapons Dealer" },
    { id = 191, name = "Carjacker" },
    { id = 192, name = "Thief" },
    { id = 193, name = "Bounty" },
    { id = 194, name = "Hitman" },
    { id = 195, name = "Assassin" },
    { id = 196, name = "Rival" },
    { id = 197, name = "Leader" },
    { id = 198, name = "Boss" },
    { id = 199, name = "Kingpin" },
    { id = 200, name = "King" },
    { id = 201, name = "Queen" },
    { id = 202, name = "Prince" },
    { id = 203, name = "Princess" },
    { id = 204, name = "Knight" },
    { id = 205, name = "Bishop" },
    { id = 206, name = "Rook" },
    { id = 207, name = "Pawn" },
    { id = 208, name = "Spy" },
    { id = 209, name = "Agent" },
    { id = 210, name = "Informant" },
    { id = 211, name = "Witness" },
    { id = 212, name = "Juror" },
    { id = 213, name = "Judge" },
    { id = 214, name = "Lawyer" },
    { id = 215, name = "Celebrity" },
    { id = 216, name = "Actor" },
    { id = 217, name = "Singer" },
    { id = 218, name = "Model" },
    { id = 219, name = "Athlete" },
    { id = 220, name = "Politician" },
    { id = 221, name = "Businessman" },
    { id = 222, name = "Tycoon" },
    { id = 223, name = "Philanthropist" },
    { id = 224, name = "Scientist" },
    { id = 225, name = "Doctor" },
    { id = 226, name = "Nurse" },
    { id = 227, name = "Paramedic" },
    { id = 228, name = "Firefighter" },
    { id = 229, name = "Lifeguard" },
    { id = 230, name = "Security Guard" },
    { id = 231, name = "Bouncer" },
    { id = 232, name = "Bodyguard" },
    { id = 233, name = "Mercenary" },
    { id = 234, name = "Soldier" },
    { id = 235, name = "Veteran" },
    { id = 236, name = "Pilot" },
    { id = 237, name = "Captain" },
    { id = 238, name = "Sailor" },
    { id = 239, name = "Fisherman" },
    { id = 240, name = "Diver" },
    { id = 241, name = "Surfer" },
    { id = 242, name = "Skater" },
    { id = 243, name = "Cyclist" },
    { id = 244, name = "Runner" },
    { id = 245, name = "Swimmer" },
    { id = 246, name = "Bodybuilder" },
    { id = 247, name = "Martial Artist" },
    { id = 248, name = "Boxer" },
    { id = 249, name = "Wrestler" },
    { id = 250, name = "Fighter" },
    { id = 251, name = "Hunter" },
    { id = 252, name = "Tracker" },
    { id = 253, name = "Survivalist" },
    { id = 254, name = "Camping" },
    { id = 255, name = "Hiking" },
    { id = 256, name = "Climbing" },
    { id = 257, name = "Base Jumping" },
    { id = 258, name = "Skydiving" },
    { id = 259, name = "Bungee" },
    { id = 260, name = "Zip Line" },
    { id = 261, name = "Off Road" },
    { id = 262, name = "Motocross" },
    { id = 263, name = "Drag Racing" },
    { id = 264, name = "Drift" },
    { id = 265, name = "Rally" },
    { id = 266, name = "Formula" },
    { id = 267, name = "NASCAR" },
    { id = 268, name = "Indy" },
    { id = 269, name = "Monster Truck" },
    { id = 270, name = "Truck Racing" },
    { id = 271, name = "Boat Racing" },
    { id = 272, name = "Jet Ski" },
    { id = 273, name = "Yacht" },
    { id = 274, name = "Sailing" },
    { id = 275, name = "Fishing" },
    { id = 276, name = "Whale Watching" },
    { id = 277, name = "Shark" },
    { id = 278, name = "Dolphin" },
    { id = 279, name = "Sea Lion" },
    { id = 280, name = "Beach" },
    { id = 281, name = "Pier" },
    { id = 282, name = "Marina" },
    { id = 283, name = "Dock" },
    { id = 284, name = "Ship" },
    { id = 285, name = "Lighthouse" },
    { id = 286, name = "Island" },
    { id = 287, name = "Mountain" },
    { id = 288, name = "Hill" },
    { id = 289, name = "Valley" },
    { id = 290, name = "Canyon" },
    { id = 291, name = "Cave" },
    { id = 292, name = "Tunnel" },
    { id = 293, name = "Bridge" },
    { id = 294, name = "Dam" },
    { id = 295, name = "Waterfall" },
    { id = 296, name = "Lake" },
    { id = 297, name = "River" },
    { id = 298, name = "Stream" },
    { id = 299, name = "Spring" },
    { id = 300, name = "Pond" },
    { id = 301, name = "Swamp" },
    { id = 302, name = "Desert" },
    { id = 303, name = "Dune" },
    { id = 304, name = "Oasis" },
    { id = 305, name = "Forest" },
    { id = 306, name = "Woods" },
    { id = 307, name = "Jungle" },
    { id = 308, name = "Rainforest" },
    { id = 309, name = "Tree" },
    { id = 310, name = "Bush" },
    { id = 311, name = "Flower" },
    { id = 312, name = "Garden" },
    { id = 313, name = "Park" },
    { id = 314, name = "Playground" },
    { id = 315, name = "Zoo" },
    { id = 316, name = "Aquarium" },
    { id = 317, name = "Museum" },
    { id = 318, name = "Gallery" },
    { id = 319, name = "Library" },
    { id = 320, name = "School" },
    { id = 321, name = "University" },
    { id = 322, name = "College" },
    { id = 323, name = "Stadium" },
    { id = 324, name = "Arena" },
    { id = 325, name = "Track" },
    { id = 326, name = "Field" },
    { id = 327, name = "Court" },
    { id = 328, name = "Ring" },
    { id = 329, name = "Octagon" },
    { id = 330, name = "Dojo" },
    { id = 331, name = "Gym" },
    { id = 332, name = "Spa" },
    { id = 333, name = "Salon" },
    { id = 334, name = "Massage" },
    { id = 335, name = "Sauna" },
    { id = 336, name = "Steam Room" },
    { id = 337, name = "Hot Tub" },
    { id = 338, name = "Pool" },
    { id = 339, name = "Jacuzzi" },
    { id = 340, name = "Tanning" },
    { id = 341, name = "Yoga" },
    { id = 342, name = "Pilates" },
    { id = 343, name = "Crossfit" },
    { id = 344, name = "Spin Class" },
    { id = 345, name = "Aerobics" },
    { id = 346, name = "Dance" },
    { id = 347, name = "Zumba" },
    { id = 348, name = "Kickboxing" },
    { id = 349, name = "Self Defense" },
    { id = 350, name = "Shooting Range" },
    { id = 351, name = "Gun Range" },
    { id = 352, name = "Archery" },
    { id = 353, name = "Paintball" },
    { id = 354, name = "Laser Tag" },
    { id = 355, name = "Escape Room" },
    { id = 356, name = "VR Arcade" },
    { id = 357, name = "Internet Cafe" },
    { id = 358, name = "LAN Center" },
    { id = 359, name = "Cyber Cafe" },
    { id = 360, name = "Tech Store" },
    { id = 361, name = "Electronics" },
    { id = 362, name = "Phone Store" },
    { id = 363, name = "Computer Store" },
    { id = 364, name = "Game Store" },
    { id = 365, name = "Music Store" },
    { id = 366, name = "Instrument" },
    { id = 367, name = "Record Store" },
    { id = 368, name = "Book Store" },
    { id = 369, name = "Comic Store" },
    { id = 370, name = "Hobby Shop" },
    { id = 371, name = "Toy Store" },
    { id = 372, name = "Pet Store" },
    { id = 373, name = "Vet" },
    { id = 374, name = "Kennel" },
    { id = 375, name = "Groomer" },
    { id = 376, name = "Dog Park" },
    { id = 377, name = "Cat Cafe" },
    { id = 378, name = "Animal Shelter" },
    { id = 379, name = "Farm" },
    { id = 380, name = "Ranch" },
    { id = 381, name = "Stable" },
    { id = 382, name = "Barn" },
    { id = 383, name = "Orchard" },
    { id = 384, name = "Vineyard" },
    { id = 385, name = "Winery" },
    { id = 386, name = "Brewery" },
    { id = 387, name = "Distillery" },
    { id = 388, name = "Factory" },
    { id = 389, name = "Warehouse" },
    { id = 390, name = "Industrial" },
    { id = 391, name = "Construction" },
    { id = 392, name = "Mining" },
    { id = 393, name = "Oil Rig" },
    { id = 394, name = "Power Plant" },
    { id = 395, name = "Nuclear" },
    { id = 396, name = "Solar" },
    { id = 397, name = "Wind" },
    { id = 398, name = "Water Treatment" },
    { id = 399, name = "Recycling" },
    { id = 400, name = "Junkyard" },
    { id = 401, name = "Scrapyard" },
    { id = 402, name = "Landfill" },
    { id = 403, name = "Incinerator" },
    { id = 404, name = "Compost" },
    { id = 405, name = "Dump" },
    { id = 406, name = "Waste Management" },
    { id = 407, name = "Hazardous" },
    { id = 408, name = "Chemical" },
    { id = 409, name = "Biological" },
    { id = 410, name = "Radiation" },
    { id = 411, name = "Biohazard" },
    { id = 412, name = "Toxic" },
    { id = 413, name = "Pollution" },
    { id = 414, name = "Smog" },
    { id = 415, name = "Green" },
    { id = 416, name = "Eco" },
    { id = 417, name = "Organic" },
    { id = 418, name = "Vegan" },
    { id = 419, name = "Vegetarian" },
    { id = 420, name = "Gluten Free" },
    { id = 421, name = "Halal" },
    { id = 422, name = "Kosher" },
    { id = 423, name = "Farmers Market" },
    { id = 424, name = "Food Truck" },
    { id = 425, name = "Street Food" },
    { id = 426, name = "Deli" },
    { id = 427, name = "Bakery" },
    { id = 428, name = "Butcher" },
    { id = 429, name = "Fishmonger" },
    { id = 430, name = "Greengrocer" },
    { id = 431, name = "Supermarket" },
    { id = 432, name = "Hypermarket" },
    { id = 433, name = "Department Store" },
    { id = 434, name = "Mall" },
    { id = 435, name = "Outlet" },
    { id = 436, name = "Thrift" },
    { id = 437, name = "Vintage" },
    { id = 438, name = "Antique" },
    { id = 439, name = "Flea Market" },
    { id = 440, name = "Garage Sale" },
    { id = 441, name = "Yard Sale" },
    { id = 442, name = "Auction" },
    { id = 443, name = "Pawn Shop" },
    { id = 444, name = "Jewelry" },
    { id = 445, name = "Watches" },
    { id = 446, name = "Sunglasses" },
    { id = 447, name = "Shoes" },
    { id = 448, name = "Bags" },
    { id = 449, name = "Accessories" },
    { id = 450, name = "Makeup" },
    { id = 451, name = "Perfume" },
    { id = 452, name = "Skincare" },
    { id = 453, name = "Hair Salon" },
    { id = 454, name = "Nail Salon" },
    { id = 455, name = "Eyebrows" },
    { id = 456, name = "Lashes" },
    { id = 457, name = "Waxing" },
    { id = 458, name = "Laser Hair" },
    { id = 459, name = "Botox" },
    { id = 460, name = "Plastic Surgery" },
    { id = 461, name = "Dentist" },
    { id = 462, name = "Orthodontist" },
    { id = 463, name = "Optometrist" },
    { id = 464, name = "Chiropractor" },
    { id = 465, name = "Physical Therapy" },
    { id = 466, name = "Occupational" },
    { id = 467, name = "Speech" },
    { id = 468, name = "Mental Health" },
    { id = 469, name = "Psychiatrist" },
    { id = 470, name = "Psychologist" },
    { id = 471, name = "Counselor" },
    { id = 472, name = "Therapist" },
    { id = 473, name = "Rehab" },
    { id = 474, name = "Detox" },
    { id = 475, name = "Sober Living" },
    { id = 476, name = "AA Meeting" },
    { id = 477, name = "NA Meeting" },
    { id = 478, name = "Support Group" },
    { id = 479, name = "Crisis Center" },
    { id = 480, name = "Hotline" },
    { id = 481, name = "Shelter" },
    { id = 482, name = "Soup Kitchen" },
    { id = 483, name = "Food Bank" },
    { id = 484, name = "Charity" },
    { id = 485, name = "Donation" },
    { id = 486, name = "Volunteer" },
    { id = 487, name = "Community" },
    { id = 488, name = "Senior Center" },
    { id = 489, name = "Youth Center" },
    { id = 490, name = "Boys Club" },
    { id = 491, name = "Girls Club" },
    { id = 492, name = "YMCA" },
    { id = 493, name = "JCC" },
    { id = 494, name = "Church" },
    { id = 495, name = "Mosque" },
    { id = 496, name = "Synagogue" },
    { id = 497, name = "Temple" },
    { id = 498, name = "Shrine" },
    { id = 499, name = "Cathedral" },
    { id = 500, name = "Chapel" },
    { id = 501, name = "Monastery" },
    { id = 502, name = "Convent" },
    { id = 503, name = "Retreat" },
    { id = 504, name = "Meditation" },
    { id = 505, name = "Yoga Studio" },
    { id = 506, name = "Pilates Studio" },
    { id = 507, name = "Dance Studio" },
    { id = 508, name = "Art Studio" },
    { id = 509, name = "Music Studio" },
    { id = 510, name = "Recording" },
    { id = 511, name = "Radio" },
    { id = 512, name = "TV Station" },
    { id = 513, name = "Newspaper" },
    { id = 514, name = "Magazine" },
    { id = 515, name = "Publisher" },
    { id = 516, name = "Printer" },
    { id = 517, name = "Copy Shop" },
    { id = 518, name = "Office Supply" },
    { id = 519, name = "Furniture" },
    { id = 520, name = "Appliance" },
    { id = 521, name = "Mattress" },
    { id = 522, name = "Carpet" },
    { id = 523, name = "Flooring" },
    { id = 524, name = "Lighting" },
    { id = 525, name = "Hardware" },
    { id = 526, name = "Lumber" },
    { id = 527, name = "Building Supply" },
    { id = 528, name = "Garden Center" },
    { id = 529, name = "Nursery" },
    { id = 530, name = "Landscaping" },
    { id = 531, name = "Lawn Care" },
    { id = 532, name = "Tree Service" },
    { id = 533, name = "Plumber" },
    { id = 534, name = "Electrician" },
    { id = 535, name = "HVAC" },
    { id = 536, name = "Roofer" },
    { id = 537, name = "Painter" },
    { id = 538, name = "Handyman" },
    { id = 539, name = "Contractor" },
    { id = 540, name = "Architect" },
    { id = 541, name = "Engineer" },
    { id = 542, name = "Surveyor" },
    { id = 543, name = "Inspector" },
    { id = 544, name = "Appraiser" },
    { id = 545, name = "Real Estate" },
    { id = 546, name = "Mortgage" },
    { id = 547, name = "Title Company" },
    { id = 548, name = "Escrow" },
    { id = 549, name = "Notary" },
    { id = 550, name = "Courier" },
    { id = 551, name = "Delivery" },
    { id = 552, name = "Shipping" },
    { id = 553, name = "Freight" },
    { id = 554, name = "Logistics" },
    { id = 555, name = "Warehouse" },
    { id = 556, name = "Distribution" },
    { id = 557, name = "Trucking" },
    { id = 558, name = "Moving" },
    { id = 559, name = "Storage" },
    { id = 560, name = "Self Storage" },
    { id = 561, name = "Container" },
    { id = 562, name = "Crate" },
    { id = 563, name = "Box" },
    { id = 564, name = "Packaging" },
    { id = 565, name = "Supplies" },
    { id = 566, name = "Equipment" },
    { id = 567, name = "Rental" },
    { id = 568, name = "Leasing" },
    { id = 569, name = "Sales" },
    { id = 570, name = "Service" },
    { id = 571, name = "Repair" },
    { id = 572, name = "Maintenance" },
    { id = 573, name = "Installation" },
    { id = 574, name = "Cleaning" },
    { id = 575, name = "Janitorial" },
    { id = 576, name = "Maid" },
    { id = 577, name = "Housekeeping" },
    { id = 578, name = "Laundry" },
    { id = 579, name = "Dry Cleaning" },
    { id = 580, name = "Tailor" },
    { id = 581, name = "Seamstress" },
    { id = 582, name = "Cobbler" },
    { id = 583, name = "Watchmaker" },
    { id = 584, name = "Locksmith" },
    { id = 585, name = "Key Copy" },
    { id = 586, name = "Engraving" },
    { id = 587, name = "Trophy" },
    { id = 588, name = "Plaque" },
    { id = 589, name = "Award" },
    { id = 590, name = "Medal" },
    { id = 591, name = "Trophy Shop" },
    { id = 592, name = "Florist" },
    { id = 593, name = "Gift Shop" },
    { id = 594, name = "Card Shop" },
    { id = 595, name = "Party Supply" },
    { id = 596, name = "Costume" },
    { id = 597, name = "Magic" },
    { id = 598, name = "Joke" },
    { id = 599, name = "Novelty" },
    { id = 600, name = "Souvenir" },
    { id = 601, name = "Tourist" },
    { id = 602, name = "Visitor" },
    { id = 603, name = "Information" },
    { id = 604, name = "Welcome Center" },
    { id = 605, name = "Rest Area" },
    { id = 606, name = "Service Plaza" },
    { id = 607, name = "Travel Center" },
    { id = 608, name = "Truck Stop" },
    { id = 609, name = "Motel 6" },
    { id = 610, name = "Super 8" },
    { id = 611, name = "Holiday Inn" },
    { id = 612, name = "Marriott" },
    { id = 613, name = "Hilton" },
    { id = 614, name = "Hyatt" },
    { id = 615, name = "Sheraton" },
    { id = 616, name = "Westin" },
    { id = 617, name = "Four Seasons" },
    { id = 618, name = "Ritz" },
    { id = 619, name = "W Hotel" },
    { id = 620, name = "Boutique" },
    { id = 621, name = "Bed Breakfast" },
    { id = 622, name = "Inn" },
    { id = 623, name = "Lodge" },
    { id = 624, name = "Resort" },
    { id = 625, name = "Spa Resort" },
    { id = 626, name = "Golf Resort" },
    { id = 627, name = "Ski Resort" },
    { id = 628, name = "Beach Resort" },
    { id = 629, name = "Casino Resort" },
    { id = 630, name = "Dude Ranch" },
    { id = 631, name = "Campground" },
    { id = 632, name = "RV Park" },
    { id = 633, name = "Trailer Park" },
    { id = 634, name = "Mobile Home" },
    { id = 635, name = "Tiny House" },
    { id = 636, name = "Treehouse" },
    { id = 637, name = "Houseboat" },
    { id = 638, name = "Floating Home" },
    { id = 639, name = "Apartment" },
    { id = 640, name = "Condo" },
    { id = 641, name = "Townhouse" },
    { id = 642, name = "Duplex" },
    { id = 643, name = "Villa" },
    { id = 644, name = "Mansion" },
    { id = 645, name = "Estate" },
    { id = 646, name = "Castle" },
    { id = 647, name = "Palace" },
    { id = 648, name = "Fortress" },
    { id = 649, name = "Tower" },
    { id = 650, name = "Skyscraper" },
    { id = 651, name = "High Rise" },
    { id = 652, name = "Mid Rise" },
    { id = 653, name = "Low Rise" },
    { id = 654, name = "Walk Up" },
    { id = 655, name = "Studio" },
    { id = 656, name = "Loft" },
    { id = 657, name = "Penthouse" },
    { id = 658, name = "Basement" },
    { id = 659, name = "Attic" },
    { id = 660, name = "Garage" },
    { id = 661, name = "Shed" },
    { id = 662, name = "Workshop" },
    { id = 663, name = "Studio" },
    { id = 664, name = "Office" },
    { id = 665, name = "Coworking" },
    { id = 666, name = "Incubator" },
    { id = 667, name = "Accelerator" },
    { id = 668, name = "Startup" },
    { id = 669, name = "Tech Hub" },
    { id = 670, name = "Innovation" },
    { id = 671, name = "Research" },
    { id = 672, name = "Lab" },
    { id = 673, name = "Testing" },
    { id = 674, name = "Prototype" },
    { id = 675, name = "Manufacturing" },
    { id = 676, name = "Assembly" },
    { id = 677, name = "Fabrication" },
    { id = 678, name = "Machining" },
    { id = 679, name = "Welding" },
    { id = 680, name = "Casting" },
    { id = 681, name = "Molding" },
    { id = 682, name = "Forging" },
    { id = 683, name = "Stamping" },
    { id = 684, name = "Printing" },
    { id = 685, name = "Publishing" },
    { id = 686, name = "Media" },
    { id = 687, name = "Broadcast" },
    { id = 688, name = "Streaming" },
    { id = 689, name = "Podcast" },
    { id = 690, name = "Webcast" },
    { id = 691, name = "YouTube" },
    { id = 692, name = "Twitch" },
    { id = 693, name = "TikTok" },
    { id = 694, name = "Instagram" },
    { id = 695, name = "Twitter" },
    { id = 696, name = "Facebook" },
    { id = 697, name = "LinkedIn" },
    { id = 698, name = "Social Media" },
    { id = 699, name = "Digital Marketing" },
    { id = 700, name = "SEO" },
    { id = 701, name = "Web Design" },
    { id = 702, name = "App Dev" },
    { id = 703, name = "Software" },
    { id = 704, name = "Hardware" },
    { id = 705, name = "Network" },
    { id = 706, name = "Server" },
    { id = 707, name = "Cloud" },
    { id = 708, name = "Database" },
    { id = 709, name = "Analytics" },
    { id = 710, name = "Big Data" },
    { id = 711, name = "AI" },
    { id = 712, name = "Machine Learning" },
    { id = 713, name = "Blockchain" },
    { id = 714, name = "Crypto" },
    { id = 715, name = "Bitcoin" },
    { id = 716, name = "Ethereum" },
    { id = 717, name = "NFT" },
    { id = 718, name = "Metaverse" },
    { id = 719, name = "VR" },
    { id = 720, name = "AR" },
    { id = 721, name = "XR" },
    { id = 722, name = "Mixed Reality" },
    { id = 723, name = "Hologram" },
    { id = 724, name = "Projection" },
    { id = 725, name = "Display" },
    { id = 726, name = "Screen" },
    { id = 727, name = "Monitor" },
    { id = 728, name = "TV" },
    { id = 729, name = "Projector" },
    { id = 730, name = "Sound" },
    { id = 731, name = "Audio" },
    { id = 732, name = "Speaker" },
    { id = 733, name = "Headphones" },
    { id = 734, name = "Microphone" },
    { id = 735, name = "Camera" },
    { id = 736, name = "Photo" },
    { id = 737, name = "Video" },
    { id = 738, name = "Film" },
    { id = 739, name = "Cinema" },
    { id = 740, name = "Theater" },
    { id = 741, name = "Stage" },
    { id = 742, name = "Performance" },
    { id = 743, name = "Concert" },
    { id = 744, name = "Festival" },
    { id = 745, name = "Fair" },
    { id = 746, name = "Carnival" },
    { id = 747, name = "Circus" },
    { id = 748, name = "Rodeo" },
    { id = 749, name = "Parade" },
    { id = 750, name = "Procession" },
    { id = 751, name = "March" },
    { id = 752, name = "Protest" },
    { id = 753, name = "Rally" },
    { id = 754, name = "Demonstration" },
    { id = 755, name = "Vigil" },
    { id = 756, name = "Memorial" },
    { id = 757, name = "Funeral" },
    { id = 758, name = "Cemetery" },
    { id = 759, name = "Graveyard" },
    { id = 760, name = "Crypt" },
    { id = 761, name = "Mausoleum" },
    { id = 762, name = "Tomb" },
    { id = 763, name = "Pyramid" },
    { id = 764, name = "Ruins" },
    { id = 765, name = "Ancient" },
    { id = 766, name = "Historical" },
    { id = 767, name = "Monument" },
    { id = 768, name = "Statue" },
    { id = 769, name = "Sculpture" },
    { id = 770, name = "Art" },
    { id = 771, name = "Mural" },
    { id = 772, name = "Graffiti" },
    { id = 773, name = "Street Art" },
    { id = 774, name = "Public Art" },
    { id = 775, name = "Fountain" },
    { id = 776, name = "Pond" },
    { id = 777, name = "Garden" },
    { id = 778, name = "Park" },
    { id = 779, name = "Plaza" },
    { id = 780, name = "Square" },
    { id = 781, name = "Courtyard" },
    { id = 782, name = "Atrium" },
    { id = 783, name = "Lobby" },
    { id = 784, name = "Entrance" },
    { id = 785, name = "Exit" },
    { id = 786, name = "Emergency" },
    { id = 787, name = "Fire Exit" },
    { id = 788, name = "Stairs" },
    { id = 789, name = "Elevator" },
    { id = 790, name = "Escalator" },
    { id = 791, name = "Ramp" },
    { id = 792, name = "Accessible" },
    { id = 793, name = "Wheelchair" },
    { id = 794, name = "Handicap" },
    { id = 795, name = "Disabled" },
    { id = 796, name = "Blind" },
    { id = 797, name = "Deaf" },
    { id = 798, name = "Assistance" },
    { id = 799, name = "Help" },
    { id = 800, name = "Info" },
    { id = 801, name = "Question" },
    { id = 802, name = "Answer" },
    { id = 803, name = "FAQ" },
    { id = 804, name = "Support" },
    { id = 805, name = "Contact" },
    { id = 806, name = "Feedback" },
    { id = 807, name = "Review" },
    { id = 808, name = "Rating" },
    { id = 809, name = "Star" },
    { id = 810, name = "Heart" },
    { id = 811, name = "Like" },
    { id = 812, name = "Share" },
    { id = 813, name = "Follow" },
    { id = 814, name = "Subscribe" },
    { id = 815, name = "Join" },
    { id = 816, name = "Register" },
    { id = 817, name = "Sign Up" },
    { id = 818, name = "Login" },
    { id = 819, name = "Logout" },
    { id = 820, name = "Profile" },
    { id = 821, name = "Settings" },
    { id = 822, name = "Preferences" },
    { id = 823, name = "Options" },
    { id = 824, name = "Config" },
    { id = 825, name = "Admin" },
    { id = 826, name = "System" }
}

BlipConfig.Colors = {
    { id = 0, name = "White", hex = "#FFFFFF" },
    { id = 1, name = "Red", hex = "#F44242" },
    { id = 2, name = "Green", hex = "#42F442" },
    { id = 3, name = "Blue", hex = "#4286F4" },
    { id = 4, name = "Yellow", hex = "#F4F442" },
    { id = 5, name = "Cyan", hex = "#42F4F4" },
    { id = 6, name = "Purple", hex = "#9B42F4" },
    { id = 7, name = "Pink", hex = "#F442C5" },
    { id = 8, name = "Orange", hex = "#F49542" },
    { id = 9, name = "Gray", hex = "#A0A0A0" },
    { id = 10, name = "Dark Gray", hex = "#5A5A5A" },
    { id = 11, name = "Light Gray", hex = "#C8C8C8" },
    { id = 12, name = "Black", hex = "#282828" },
    { id = 13, name = "Brown", hex = "#8B4513" },
    { id = 14, name = "Dark Blue", hex = "#2A3F8F" },
    { id = 15, name = "Dark Green", hex = "#1B6C1B" },
    { id = 16, name = "Dark Red", hex = "#8B1A1A" },
    { id = 17, name = "Dark Yellow", hex = "#8B8B1A" },
    { id = 18, name = "Dark Cyan", hex = "#1A8B8B" },
    { id = 19, name = "Dark Purple", hex = "#5A1A8B" },
    { id = 20, name = "Dark Pink", hex = "#8B1A5A" },
    { id = 21, name = "Dark Orange", hex = "#8B5A1A" },
    { id = 22, name = "Light Red", hex = "#F48080" },
    { id = 23, name = "Light Green", hex = "#80F480" },
    { id = 24, name = "Light Blue", hex = "#80C8F4" },
    { id = 25, name = "Light Yellow", hex = "#F4F480" },
    { id = 26, name = "Light Cyan", hex = "#80F4F4" },
    { id = 27, name = "Light Purple", hex = "#C880F4" },
    { id = 28, name = "Light Pink", hex = "#F480C8" },
    { id = 29, name = "Light Orange", hex = "#F4C880" },
    { id = 30, name = "Forest Green", hex = "#228B22" },
    { id = 31, name = "Slate Blue", hex = "#6A5ACD" },
    { id = 32, name = "Saddle Brown", hex = "#8B4513" },
    { id = 33, name = "Indian Red", hex = "#CD5C5C" },
    { id = 34, name = "Midnight Blue", hex = "#191970" },
    { id = 35, name = "Teal", hex = "#008080" },
    { id = 36, name = "Crimson", hex = "#DC143C" },
    { id = 37, name = "Dodger Blue", hex = "#1E90FF" },
    { id = 38, name = "Gold", hex = "#FFD700" },
    { id = 39, name = "Hot Pink", hex = "#FF69B4" },
    { id = 40, name = "Steel Blue", hex = "#4682B4" },
    { id = 41, name = "Dark Slate Gray", hex = "#2F4F4F" },
    { id = 42, name = "Lime", hex = "#00FF00" },
    { id = 43, name = "Coral", hex = "#FF7F50" },
    { id = 44, name = "Tomato", hex = "#FF6347" },
    { id = 45, name = "Royal Blue", hex = "#4169E1" },
    { id = 46, name = "Olive", hex = "#808000" },
    { id = 47, name = "Deep Sky Blue", hex = "#00BFFF" },
    { id = 48, name = "Magenta", hex = "#FF00FF" },
    { id = 49, name = "Sky Blue", hex = "#87CEEB" },
    { id = 50, name = "Sea Green", hex = "#2E8B57" },
    { id = 51, name = "Violet", hex = "#EE82EE" },
    { id = 52, name = "Tan", hex = "#D2B48C" },
    { id = 53, name = "Moccasin", hex = "#FFE4B5" },
    { id = 54, name = "Salmon", hex = "#FA8072" },
    { id = 55, name = "Orchid", hex = "#DA70D6" },
    { id = 56, name = "Pale Green", hex = "#98FB98" },
    { id = 57, name = "Khaki", hex = "#F0E68C" },
    { id = 58, name = "Turquoise", hex = "#40E0D0" },
    { id = 59, name = "Aqua", hex = "#00FFFF" },
    { id = 60, name = "Maroon", hex = "#800000" },
    { id = 61, name = "Navy", hex = "#000080" },
    { id = 62, name = "Aquamarine", hex = "#7FFFD4" },
    { id = 63, name = "Chartreuse", hex = "#7FFF00" },
    { id = 64, name = "Plum", hex = "#DDA0DD" },
    { id = 65, name = "Peru", hex = "#CD853F" },
    { id = 66, name = "Rosy Brown", hex = "#BC8F8F" },
    { id = 67, name = "Powder Blue", hex = "#B0E0E6" },
    { id = 68, name = "Thistle", hex = "#D8BFD8" },
    { id = 69, name = "Peach Puff", hex = "#FFDAB9" },
    { id = 70, name = "Bisque", hex = "#FFE4C4" },
    { id = 71, name = "Lavender", hex = "#E6E6FA" },
    { id = 72, name = "Blanched Almond", hex = "#FFEBCD" },
    { id = 73, name = "Misty Rose", hex = "#FFE4E1" },
    { id = 74, name = "Wheat", hex = "#F5DEB3" },
    { id = 75, name = "Antique White", hex = "#FAEBD7" },
    { id = 76, name = "Linen", hex = "#FAF0E6" },
    { id = 77, name = "Old Lace", hex = "#FDF5E6" },
    { id = 78, name = "Seashell", hex = "#FFF5EE" },
    { id = 79, name = "Snow", hex = "#FFFAFA" },
    { id = 80, name = "Floral White", hex = "#FFFAF0" },
    { id = 81, name = "Ivory", hex = "#FFFFF0" },
    { id = 82, name = "Mint Cream", hex = "#F5FFFA" },
    { id = 83, name = "Honeydew", hex = "#F0FFF0" },
    { id = 84, name = "Azure", hex = "#F0FFFF" },
    { id = 85, name = "Ghost White", hex = "#F8F8FF" }
}
